name: Invoke-Pester
description: Runs test based on PowerShell.
author: PSModule
branding:
  icon: check-square
  color: gray-dark

outputs:
  result:
    description: If the tests passed.
    value: ${{ fromJSON(steps.test.outputs.result).result }}

runs:
  using: composite
  steps:
    - name: Invoke-Pester
      uses: PSModule/GitHub-Script@v1
      id: test
      with:
        ShowOutput: true
        Script: |
          # Invoke-Pester
          ${{ github.action_path }}\scripts\main.ps1
